FROM ubuntu:24.04
LABEL org.opencontainers.image.authors="Mickael Patron"
LABEL org.opencontainers.image.source="https://github.com/mpatron/my-playbooks"
LABEL org.opencontainers.image.path="podman/ubuntu/Containerfile"
LABEL org.opencontainers.image.title="podman-ubuntu-systemd"
LABEL org.opencontainers.image.description="ubuntu9 Stream image with systemd for Podman containers and Ansible with molecule testing"
LABEL org.opencontainers.image.version="1.0.0"
LABEL org.opencontainers.image.url="https://github.com/mpatron/my-playbooks/podman/ubuntu/Containerfile"
LABEL org.opencontainers.image.vendor="JObjects.org"
LABEL org.opencontainers.image.created="2025-12-17T00:00:00Z"
LABEL org.opencontainers.image.revision="1.0.0"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.documentation="https://github.com/mpatron/my-playbooks/podman/ubuntu/readme.md"


ARG DEBIAN_FRONTEND=noninteractive

# Install: dependencies, clean: apt cache, remove dir: cache, man, doc, change mod time of cache dir.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       software-properties-common \
       rsyslog systemd systemd-cron sudo \
    && apt-get clean \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && rm -rf /var/lib/apt/lists/* \
    && touch -d "2 hours ago" /var/lib/apt/lists
RUN sed -i 's/^\($ModLoad imklog\)/#\1/' /etc/rsyslog.conf

RUN rm -f /lib/systemd/system/systemd*udev* \
  && rm -f /lib/systemd/system/getty.target

VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]
