---
all:
  children:
    webservers:
      hosts:
        web-server:
          ansible_host: web-server
          ansible_user: root
          ansible_connection: containers.podman.podman
          # container_image: quay.io/centos/centos:stream9
          container_image: localhost/podman-centos-systemd:stream9
          container_command: sleep 1d
          container_privileged: true
      vars:
        http_port: 80
        server_name: test-web
        required_packages:
          - python3
          - systemd
    databases:
      hosts:
        db-server:
          ansible_host: db-server
          ansible_user: root
          ansible_connection: containers.podman.podman
          # container_image: quay.io/centos/centos:stream9
          container_image: localhost/podman-centos-systemd:stream9
          container_command: sleep 1d
          container_privileged: true
      vars:
        db_name: testdb
        db_user: testuser
        required_packages:
          - python3
          - systemd
