FROM docker.io/almalinux:10
LABEL org.opencontainers.image.authors="Mickael Patron"
LABEL org.opencontainers.image.source="https://github.com/mpatron/my-playbooks"
LABEL org.opencontainers.image.path="podman/almalinux/Containerfile"
LABEL org.opencontainers.image.title="podman-almalinux-systemd"
LABEL org.opencontainers.image.description="almalinux9 Stream image with systemd for Podman containers and Ansible with molecule testing"
LABEL org.opencontainers.image.version="1.0.0"
LABEL org.opencontainers.image.url="https://github.com/mpatron/my-playbooks/podman/almalinux/Containerfile"
LABEL org.opencontainers.image.vendor="JObjects.org"
LABEL org.opencontainers.image.created="2025-12-17T00:00:00Z"
LABEL org.opencontainers.image.revision="1.0.0"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.documentation="https://github.com/mpatron/my-playbooks/podman/almalinux/readme.md"


# Installer systemd, rsyslog et sudo
RUN dnf --assumeyes --quiet update \
    && dnf --assumeyes --quiet install \
       rsyslog systemd sudo \
    && dnf --assumeyes --quiet clean all \
    && rm -rf /usr/share/doc /usr/share/man /var/cache/dnf

# Désactiver imklog dans rsyslog
RUN sed -i 's/^\($ModLoad imklog\)/#\1/' /etc/rsyslog.conf

# Supprimer certains services inutiles dans un conteneur
RUN rm -rf /usr/lib/systemd/system/systemd*udev* \
  && rm -rf /usr/lib/systemd/system/getty.target

# Monter les volumes nécessaires à systemd
VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]

# Lancer systemd comme PID 1
CMD ["/lib/systemd/systemd"]