---
- name: "== Create == Create container instances"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "== Create == Afficher le chemin du scénario"
      ansible.builtin.debug:
        msg: "Scénario en cours : {{ molecule_scenario_directory }}"

    - name: "== Create == Lire la config Molecule"
      ansible.builtin.debug:
        var: molecule_yml.driver.name

    - name: "== Create == Create container network"
      containers.podman.podman_network:
        name: molecule-linux-test
        state: present

    - name: "== Create == Create test containers"
      containers.podman.podman_container:
        name: "{{ hostvars[item].ansible_host }}"
        image: "{{ hostvars[item].container_image }}"
        # command: doit être commenté pour que systemd fonctionne correctement
        # Biensur, on pourrait aussi le mettre  pour faire des tests qui ne 
        # nécessite pas systemd.
        # command: "{{ hostvars[item].container_command }}"
        privileged: "{{ hostvars[item].container_privileged }}"
        state: started
        network:
          - molecule-linux-test
        systemd: true
      loop: "{{ groups['all'] }}"

    - name: "== Create == Wait for containers to be ready"
      ansible.builtin.wait_for_connection:
        timeout: 300
      delegate_to: "{{ hostvars[item].ansible_host }}"
      loop: "{{ groups['all'] }}"
