---
dependency:
  name: galaxy
  options:
    # requirements-file: ../requirements.yml
    role-file: "{{ molecule_scenario_directory }}/requirements.yml"
    requirements-file: "{{ molecule_scenario_directory }}/requirements.yml"
    # role-file: "/tmp/my-playbooks/molecule/linux/requirements.yml"
    # requirements-file: "/tmp/my-playbooks/molecule/linux/requirements.yml"

ansible:
  cfg:
    defaults:
      deprecation_warnings: false
      collections_path: collections
      # inventory: inventory/hosts.yml
      # inventory: "{{ molecule_scenario_directory }}/inventory.yml"
  executor:
    args:
      ansible_playbook:
        - --inventory=inventory/

scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
