---
- name: "== Verify == Task"
  hosts: all
  gather_facts: true
  tasks:
    - name: "== Verify == Check required packages are installed"
      ansible.builtin.package_facts:
        manager: auto

    - name: "== Verify == Verify python3 is installed"
      ansible.builtin.assert:
        that:
          - "'python3' in ansible_facts.packages"
        fail_msg: "Python3 package not found"

    - name: "== Verify == Verify systemd service is running"
      ansible.builtin.systemd:
        name: systemd-logind
        state: started
      check_mode: true
      register: systemd_check
      failed_when: false

    - name: "== Verify == Assert systemd is active"
      ansible.builtin.assert:
        that:
          - systemd_check is not failed
        fail_msg: "Systemd service not running"
